services:
  - type: web
    name: house-price-backend
    runtime: python
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn --chdir backend app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
